run:
  skip-dirs-use-default: false
  tests: true

issues:
  max-same-issues: 0

  exclude:
    - "exported:"
    - G404 # weak random number generator

  exclude-rules:
    - path: examples/03-go-errors-concept/errorf-\d/main\.go
      linters:
        - govet

    - path: _test\.go
      linters:
        - dupl
        - funlen
        - gosec

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - exportloopref
    - funlen
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ifshort
    - ineffassign
    - misspell
    - nestif
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
