# https://taskfile.dev/#/installation
version: '3'

silent: true

tasks:
  default:
    cmds:
      - task: tools:install
      - task: tidy
      - task: fmt
      - task: lint

  tools:install:
    - echo "Install local tools..."
    - GO111MODULE=off go get -u mvdan.cc/gofumpt
    - GO111MODULE=off go get -u github.com/daixiang0/gci

  tidy:
    cmds:
      - echo "Tidy..."
      - go mod tidy

  fmt:
    cmds:
      - echo "Fmt..."
      - gofumpt -w .
      - gci -w . > /dev/null

  lint:
    cmds:
      - echo "Lint..."
      - golangci-lint run --fix ./...
